### ISSUE TITLE
[Google Play] Crash when viewing downloads (probally specific devices only)

### ISSUE THREAD

**Issue by mTwTm** [mozilla-mobile/FirefoxLite#2543]
Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW_DOWNLOADS flg=0x10000000 }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1809)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
       at android.app.Activity.startActivityForResult(Activity.java:3964)
       at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
       at android.app.Activity.startActivityForResult(Activity.java:3925)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:751)
       at android.app.Activity.startActivity(Activity.java:4248)
       at android.app.Activity.startActivity(Activity.java:4216)
       at org.mozilla.focus.utils.IntentUtils.openDownloadPage(IntentUtils.java:202)
       at org.mozilla.focus.utils.IntentUtils.intentOpenFile(IntentUtils.java:192)
       at org.mozilla.focus.widget.DownloadListAdapter$5$1$1.run(DownloadListAdapter.java:323)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5710)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)

**Comment by manddy** [comment]
@mTwTm I would like to work on this issue but the issue is somewhat unclear .Can you please explain the issue in descriptive manner ?

**Comment by mTwTm** [comment]
Thanks, manddy!

This is what I can interpret from the stack trace: `No Activity found to handle Intent { act=android.intent.action.VIEW_DOWNLOADS flg=0x10000000` implies the intent we fired in IntentUtils.openDownloadPage might have lead to a result when on specific devices we don't have any Activity to handle this intent
