### ISSUE TITLE
BitmapFactory.decodeResource(getResources(), R.drawable.home_pattern) returns null

### ISSUE THREAD

**Issue by mTwTm** [mozilla-mobile/FirefoxLite#3010]
Stack trace:

Caused by java.lang.IllegalArgumentException: Bitmap must be non-null
       at android.graphics.BitmapShader.<init>(BitmapShader.java:49)
       at android.graphics.BitmapShader.<init>(BitmapShader.java:44)
       at org.mozilla.focus.home.HomeScreenBackground.init(HomeScreenBackground.java:54)
       at org.mozilla.focus.home.HomeScreenBackground.<init>(HomeScreenBackground.java:41)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
       at android.view.LayoutInflater.createView(LayoutInflater.java:647)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at org.mozilla.focus.home.HomeFragment.onCreateView(HomeFragment.java:367)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
       at org.mozilla.focus.activity.MainActivity.onStart(MainActivity.java:263)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1335)
       at android.app.Activity.performStart(Activity.java:7033)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2744)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6518)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

Caused by java.lang.IllegalArgumentException: Bitmap must be non-null
       at android.graphics.BitmapShader.<init>(BitmapShader.java:49)
       at android.graphics.BitmapShader.<init>(BitmapShader.java:44)
       at org.mozilla.focus.home.HomeScreenBackground.init(HomeScreenBackground.java:54)
       at org.mozilla.focus.home.HomeScreenBackground.<init>(HomeScreenBackground.java:41)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
       at android.view.LayoutInflater.createView(LayoutInflater.java:647)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361)
       at android.view.LayoutInflater.inflate(<Xposed>)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at org.mozilla.focus.home.HomeFragment.onCreateView(HomeFragment.java:367)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
       at org.mozilla.focus.activity.MainActivity.onStart(MainActivity.java:263)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
       at android.app.Activity.performStart(Activity.java:7029)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

**Comment by mTwTm** [comment]
Suspecting this is a crash after enabling aab given we did not change this part for a while.

**Comment by chianger** [comment]
decision from the triage: we'll take this fix and live without the apk size gain for now.
