### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException at org.mozilla.focus.widget.ShiftDrawable.draw

### ISSUE THREAD

**Issue by mTwTm** [mozilla-mobile/FirefoxLite#3042]
Regression of 1.0.7

Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'long android.graphics.Path.mNativePath' on a null object reference
       at android.view.GLES20Canvas.clipPath(GLES20Canvas.java:281)
       at org.mozilla.focus.widget.ShiftDrawable.draw(ShiftDrawable.java:90)
       at android.widget.ProgressBar.drawTrack(ProgressBar.java:1767)
       at android.widget.ProgressBar.onDraw(ProgressBar.java:1734)
       at org.mozilla.focus.widget.AnimatedProgressBar.onDraw(AnimatedProgressBar.java:180)
       at android.view.View.draw(View.java:16536)
       at android.view.View.updateDisplayListIfDirty(View.java:15466)
       at android.view.View.getDisplayList(View.java:15488)
       at android.view.View.draw(View.java:16258)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
       at android.view.View.updateDisplayListIfDirty(View.java:15461)
       at android.view.View.getDisplayList(View.java:15488)
       at android.view.View.draw(View.java:16258)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
       at android.view.View.draw(View.java:16539)
       at android.view.View.updateDisplayListIfDirty(View.java:15466)
       at android.view.View.getDisplayList(View.java:15488)
       at android.view.View.draw(View.java:16258)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
       at android.view.View.draw(View.java:16539)
       at android.view.View.updateDisplayListIfDirty(View.java:15466)
       at android.view.View.getDisplayList(View.java:15488)
       at android.view.View.draw(View.java:16258)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
       at android.view.View.draw(View.java:16539)
       at android.view.View.updateDisplayListIfDirty(View.java:15466)
       at android.view.View.getDisplayList(View.java:15488)
       at android.view.View.draw(View.java:16258)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
       at android.view.View.updateDisplayListIfDirty(View.java:15461)
       at android.view.View.getDisplayList(View.java:15488)
       at android.view.View.draw(View.java:16258)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
       at android.view.View.updateDisplayListIfDirty(View.java:15461)
       at android.view.View.getDisplayList(View.java:15488)
       at android.view.View.draw(View.java:16258)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
       at android.view.View.updateDisplayListIfDirty(View.java:15461)
       at android.view.View.getDisplayList(View.java:15488)
       at android.view.View.draw(View.java:16258)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
       at android.view.View.updateDisplayListIfDirty(View.java:15461)
       at android.view.View.getDisplayList(View.java:15488)
       at android.view.View.draw(View.java:16258)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
       at android.view.View.updateDisplayListIfDirty(View.java:15461)
       at android.view.View.getDisplayList(View.java:15488)
       at android.view.View.draw(View.java:16258)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
       at android.view.View.updateDisplayListIfDirty(View.java:15461)
       at android.view.View.getDisplayList(View.java:15488)
       at android.view.View.draw(View.java:16258)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3713)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3506)
       at android.view.View.draw(View.java:16539)
       at android.widget.FrameLayout.draw(FrameLayout.java:598)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:3111)
       at android.view.View.updateDisplayListIfDirty(View.java:15466)
       at android.view.View.getDisplayList(View.java:15488)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:309)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:315)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:354)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2956)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2753)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2339)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1314)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7057)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:829)
       at android.view.Choreographer.doCallbacks(Choreographer.java:606)
       at android.view.Choreographer.doFrame(Choreographer.java:576)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:815)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6934)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by cnevinc** [comment]
See it on Firebase: https://console.firebase.google.com/u/1/project/zerda-dcf76/crashlytics/app/android:org.mozilla.rocket/issues/5c2952f1f8b88c2963b78a34?time=last-seven-days&sessionId=5C2952B4014E0001301068AB9674B194_DNE_0_v2

Looking at the crashes, maybe we can reproduce it using 5.1 devices.

**Comment by Daisy-pliu** [comment]
try on physical device can not find STR.
Test device: sony Xperia
Test OS: 5.0.2
