### ISSUE TITLE
Multiple StrictMode Violation when UrlInputFragment created

### ISSUE THREAD

**Issue by mTwTm** [mozilla-mobile/FirefoxLite#3458]
2019-04-15 11:03:37.529 904-5598/? W/ActivityManager: handleApplicationStrictModeViolation; res=0
2019-04-15 11:03:40.562 16362-16362/org.mozilla.rocket.debug.tyu D/StrictMode: StrictMode policy violation; ~duration=240 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:241)
        at java.io.File.isDirectory(File.java:845)
        at dalvik.system.DexPathList$Element.toString(DexPathList.java:681)
        at java.lang.String.valueOf(String.java:2896)
        at java.util.Arrays.toString(Arrays.java:4511)
        at dalvik.system.DexPathList.toString(DexPathList.java:201)
        at java.lang.String.valueOf(String.java:2896)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at aDK.f(PG:31)
        at aDK.<init>(PG:2)
        at aDJ.a(PG:4)
        at aAZ.run(Unknown Source:24)
        at org.chromium.base.ThreadUtils.a(PG:10)
        at xN.c(PG:113)
        at xN.b(PG:180)
        at xN.e(PG:197)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(PG:214)
        at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1266)
        at org.mozilla.focus.web.WebViewProvider.buildUserAgentString(WebViewProvider.java:181)
        at org.mozilla.focus.web.WebViewProvider.getUserAgentString(WebViewProvider.java:209)
        at org.mozilla.focus.urlinput.UrlInputFragment.onCreate(UrlInputFragment.kt:59)
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2414)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
        at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195)
        at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078)
        at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:117)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-04-15 11:03:41.843 904-923/? W/ActivityManager: handleApplicationStrictModeViolation; res=0
2019-04-15 11:03:41.847 16362-16362/org.mozilla.rocket.debug.tyu D/StrictMode: StrictMode policy violation; ~duration=240 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:241)
        at java.io.File.isDirectory(File.java:845)
        at dalvik.system.DexPathList$Element.toString(DexPathList.java:681)
        at java.lang.String.valueOf(String.java:2896)
        at java.util.Arrays.toString(Arrays.java:4511)
        at dalvik.system.DexPathList.toString(DexPathList.java:201)
        at java.lang.String.valueOf(String.java:2896)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at aDK.f(PG:31)
        at aDK.<init>(PG:2)
        at aDJ.a(PG:4)
        at aAZ.run(Unknown Source:24)
        at org.chromium.base.ThreadUtils.a(PG:10)
        at xN.c(PG:113)
        at xN.b(PG:180)
        at xN.e(PG:197)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(PG:214)
        at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1266)
        at org.mozilla.focus.web.WebViewProvider.buildUserAgentString(WebViewProvider.java:181)
        at org.mozilla.focus.web.WebViewProvider.getUserAgentString(WebViewProvider.java:209)
        at org.mozilla.focus.urlinput.UrlInputFragment.onCreate(UrlInputFragment.kt:59)
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2414)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
        at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195)
        at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078)
        at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:117)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-04-15 11:03:43.017 16362-16362/org.mozilla.rocket.debug.tyu D/StrictMode: StrictMode policy violation; ~duration=240 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:241)
        at java.io.File.isDirectory(File.java:845)
        at dalvik.system.DexPathList$Element.toString(DexPathList.java:681)
        at java.lang.String.valueOf(String.java:2896)
        at java.util.Arrays.toString(Arrays.java:4511)
        at dalvik.system.DexPathList.toString(DexPathList.java:201)
        at java.lang.String.valueOf(String.java:2896)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at aDK.f(PG:31)
        at aDK.<init>(PG:2)
        at aDJ.a(PG:4)
        at aAZ.run(Unknown Source:24)
        at org.chromium.base.ThreadUtils.a(PG:10)
        at xN.c(PG:113)
        at xN.b(PG:180)
        at xN.e(PG:197)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(PG:214)
        at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1266)
        at org.mozilla.focus.web.WebViewProvider.buildUserAgentString(WebViewProvider.java:181)
        at org.mozilla.focus.web.WebViewProvider.getUserAgentString(WebViewProvider.java:209)
        at org.mozilla.focus.urlinput.UrlInputFragment.onCreate(UrlInputFragment.kt:59)
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2414)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
        at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195)
        at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078)
        at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:117)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-04-15 11:03:44.272 16362-16362/org.mozilla.rocket.debug.tyu D/StrictMode: StrictMode policy violation; ~duration=240 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:241)
        at java.io.File.isDirectory(File.java:845)
        at dalvik.system.DexPathList$Element.toString(DexPathList.java:681)
        at java.lang.String.valueOf(String.java:2896)
        at java.util.Arrays.toString(Arrays.java:4511)
        at dalvik.system.DexPathList.toString(DexPathList.java:201)
        at java.lang.String.valueOf(String.java:2896)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at aDK.f(PG:31)
        at aDK.<init>(PG:2)
        at aDJ.a(PG:4)
        at aAZ.run(Unknown Source:24)
        at org.chromium.base.ThreadUtils.a(PG:10)
        at xN.c(PG:113)
        at xN.b(PG:180)
        at xN.e(PG:197)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(PG:214)
        at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1266)
        at org.mozilla.focus.web.WebViewProvider.buildUserAgentString(WebViewProvider.java:181)
        at org.mozilla.focus.web.WebViewProvider.getUserAgentString(WebViewProvider.java:209)
        at org.mozilla.focus.urlinput.UrlInputFragment.onCreate(UrlInputFragment.kt:59)
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2414)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
        at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195)
        at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078)
        at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:117)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-04-15 11:03:45.541 16362-16362/org.mozilla.rocket.debug.tyu D/StrictMode: StrictMode policy violation; ~duration=240 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:241)
        at java.io.File.isDirectory(File.java:845)
        at dalvik.system.DexPathList$Element.toString(DexPathList.java:681)
        at java.lang.String.valueOf(String.java:2896)
        at java.util.Arrays.toString(Arrays.java:4511)
        at dalvik.system.DexPathList.toString(DexPathList.java:201)
        at java.lang.String.valueOf(String.java:2896)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at aDK.f(PG:31)
        at aDK.<init>(PG:2)
        at aDJ.a(PG:4)
        at aAZ.run(Unknown Source:24)
        at org.chromium.base.ThreadUtils.a(PG:10)
        at xN.c(PG:113)
        at xN.b(PG:180)
        at xN.e(PG:197)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(PG:214)
        at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1266)
        at org.mozilla.focus.web.WebViewProvider.buildUserAgentString(WebViewProvider.java:181)
        at org.mozilla.focus.web.WebViewProvider.getUserAgentString(WebViewProvider.java:209)
        at org.mozilla.focus.urlinput.UrlInputFragment.onCreate(UrlInputFragment.kt:59)
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2414)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
        at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195)
        at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078)
        at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:117)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-04-15 11:03:47.079 16362-16362/org.mozilla.rocket.debug.tyu D/StrictMode: StrictMode policy violation; ~duration=240 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:241)
        at java.io.File.isDirectory(File.java:845)
        at dalvik.system.DexPathList$Element.toString(DexPathList.java:681)
        at java.lang.String.valueOf(String.java:2896)
        at java.util.Arrays.toString(Arrays.java:4511)
        at dalvik.system.DexPathList.toString(DexPathList.java:201)
        at java.lang.String.valueOf(String.java:2896)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at aDK.f(PG:31)
        at aDK.<init>(PG:2)
        at aDJ.a(PG:4)
        at aAZ.run(Unknown Source:24)
        at org.chromium.base.ThreadUtils.a(PG:10)
        at xN.c(PG:113)
        at xN.b(PG:180)
        at xN.e(PG:197)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(PG:214)
        at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1266)
        at org.mozilla.focus.web.WebViewProvider.buildUserAgentString(WebViewProvider.java:181)
        at org.mozilla.focus.web.WebViewProvider.getUserAgentString(WebViewProvider.java:209)
        at org.mozilla.focus.urlinput.UrlInputFragment.onCreate(UrlInputFragment.kt:59)
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2414)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
        at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195)
        at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078)
        at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:117)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-04-15 11:03:48.601 16362-16362/org.mozilla.rocket.debug.tyu D/StrictMode: StrictMode policy violation; ~duration=239 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:241)
        at java.io.File.isDirectory(File.java:845)
        at dalvik.system.DexPathList$Element.toString(DexPathList.java:681)
        at java.lang.String.valueOf(String.java:2896)
        at java.util.Arrays.toString(Arrays.java:4511)
        at dalvik.system.DexPathList.toString(DexPathList.java:201)
        at java.lang.String.valueOf(String.java:2896)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at aDK.f(PG:31)
        at aDK.<init>(PG:2)
        at aDJ.a(PG:4)
        at aAZ.run(Unknown Source:24)
        at org.chromium.base.ThreadUtils.a(PG:10)
        at xN.c(PG:113)
        at xN.b(PG:180)
        at xN.e(PG:197)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(PG:214)
        at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1266)
        at org.mozilla.focus.web.WebViewProvider.buildUserAgentString(WebViewProvider.java:181)
        at org.mozilla.focus.web.WebViewProvider.getUserAgentString(WebViewProvider.java:209)
        at org.mozilla.focus.urlinput.UrlInputFragment.onCreate(UrlInputFragment.kt:59)
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2414)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
        at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195)
        at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078)
        at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:117)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-04-15 11:03:49.821 16362-16362/org.mozilla.rocket.debug.tyu D/StrictMode: StrictMode policy violation; ~duration=239 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:241)
        at java.io.File.isDirectory(File.java:845)
        at dalvik.system.DexPathList$Element.toString(DexPathList.java:681)
        at java.lang.String.valueOf(String.java:2896)
        at java.util.Arrays.toString(Arrays.java:4511)
        at dalvik.system.DexPathList.toString(DexPathList.java:201)
        at java.lang.String.valueOf(String.java:2896)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at aDK.f(PG:31)
        at aDK.<init>(PG:2)
        at aDJ.a(PG:4)
        at aAZ.run(Unknown Source:24)
        at org.chromium.base.ThreadUtils.a(PG:10)
        at xN.c(PG:113)
        at xN.b(PG:180)
        at xN.e(PG:197)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(PG:214)
        at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1266)
        at org.mozilla.focus.web.WebViewProvider.buildUserAgentString(WebViewProvider.java:181)
        at org.mozilla.focus.web.WebViewProvider.getUserAgentString(WebViewProvider.java:209)
        at org.mozilla.focus.urlinput.UrlInputFragment.onCreate(UrlInputFragment.kt:59)
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2414)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
        at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195)
        at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078)
        at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:117)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-04-15 11:03:51.143 16362-16362/org.mozilla.rocket.debug.tyu D/StrictMode: StrictMode policy violation; ~duration=239 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:241)
        at java.io.File.isDirectory(File.java:845)
        at dalvik.system.DexPathList$Element.toString(DexPathList.java:681)
        at java.lang.String.valueOf(String.java:2896)
        at java.util.Arrays.toString(Arrays.java:4511)
        at dalvik.system.DexPathList.toString(DexPathList.java:201)
        at java.lang.String.valueOf(String.java:2896)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at aDK.f(PG:31)
        at aDK.<init>(PG:2)
        at aDJ.a(PG:4)
        at aAZ.run(Unknown Source:24)
        at org.chromium.base.ThreadUtils.a(PG:10)
        at xN.c(PG:113)
        at xN.b(PG:180)
        at xN.e(PG:197)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(PG:214)
        at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1266)
        at org.mozilla.focus.web.WebViewProvider.buildUserAgentString(WebViewProvider.java:181)
        at org.mozilla.focus.web.WebViewProvider.getUserAgentString(WebViewProvider.java:209)
        at org.mozilla.focus.urlinput.UrlInputFragment.onCreate(UrlInputFragment.kt:59)
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2414)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
        at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195)
        at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078)
        at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:117)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-04-15 11:03:52.395 16362-16362/org.mozilla.rocket.debug.tyu D/StrictMode: StrictMode policy violation; ~duration=238 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:241)
        at java.io.File.isDirectory(File.java:845)
        at dalvik.system.DexPathList$Element.toString(DexPathList.java:681)
        at java.lang.String.valueOf(String.java:2896)
        at java.util.Arrays.toString(Arrays.java:4511)
        at dalvik.system.DexPathList.toString(DexPathList.java:201)
        at java.lang.String.valueOf(String.java:2896)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at aDK.f(PG:31)
        at aDK.<init>(PG:2)
        at aDJ.a(PG:4)
        at aAZ.run(Unknown Source:24)
        at org.chromium.base.ThreadUtils.a(PG:10)
        at xN.c(PG:113)
        at xN.b(PG:180)
        at xN.e(PG:197)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(PG:214)
        at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1266)
        at org.mozilla.focus.web.WebViewProvider.buildUserAgentString(WebViewProvider.java:181)
        at org.mozilla.focus.web.WebViewProvider.getUserAgentString(WebViewProvider.java:209)
        at org.mozilla.focus.urlinput.UrlInputFragment.onCreate(UrlInputFragment.kt:59)
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2414)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
        at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195)
        at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078)
        at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:117)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by mTwTm** [comment]
What I really care about is there are 10 buildUserAgentString calls and this call is...super slow. It was supposed to be cached but seems like it's not.

They are so annoying so I feel like this was not surfacing until now because of the buildUserAgentString not being caught as a violation?

**Comment by mTwTm** [comment]
So basically the buildUserAgentString is actually only trigged once but it just takes too long so violations are reported multiple times.

**Comment by mTwTm** [comment]
After a brief evaluation/contemplation I decided to keep this as is for now. Only 25% sessions open UrlInputs so doing this earlier may not be a good idea.

**Comment by mTwTm** [comment]
I'm going to keep this issue open but I've just whitelisted it in the pr.
