### ISSUE TITLE
StrictMode violation when MainActivity Created (PinSiteManager)

### ISSUE THREAD

**Issue by mTwTm** [mozilla-mobile/FirefoxLite#3459]
2019-04-15 11:03:35.897 16362-16362/org.mozilla.rocket.debug.tyu D/StrictMode: StrictMode policy violation; ~duration=64 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:251)
        at java.io.File.exists(File.java:815)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:605)
        at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:596)
        at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:552)
        at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:747)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:400)
        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:174)
        at org.mozilla.rocket.home.pinsite.SharedPreferencePinSiteDelegate.<init>(PinSiteManager.kt:67)
        at org.mozilla.rocket.home.pinsite.PinSiteManagerKt.getPinSiteManager(PinSiteManager.kt:27)
        at org.mozilla.focus.home.HomeFragment.onActivityCreated(HomeFragment.java:637)
        at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2460)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1483)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at org.mozilla.focus.activity.MainActivity.onStart(MainActivity.java:268)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7157)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by mTwTm** [comment]
Triggered by:
org.mozilla.rocket.home.pinsite.PinSiteManager
`private val pref = context.getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE)`

**Comment by mTwTm** [comment]
@pharspher Do you feel like there's a better way to do this? Or let me know if you feel like we can live with it.

**Comment by mTwTm** [comment]
I'm going to temp allow this but I'll keep this ticket open.
