### ISSUE TITLE
StrictMode violation when creating Webview

### ISSUE THREAD

**Issue by mTwTm** [mozilla-mobile/FirefoxLite#3466]
2019-04-15 18:22:41.611 904-4543/? W/ActivityManager: handleApplicationStrictModeViolation; res=0
2019-04-15 18:22:42.122 1806-1806/org.mozilla.rocket.debug.tyu D/StrictMode: StrictMode policy violation; ~duration=272 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:241)
        at java.io.File.isDirectory(File.java:845)
        at dalvik.system.DexPathList$Element.toString(DexPathList.java:681)
        at java.lang.String.valueOf(String.java:2896)
        at java.util.Arrays.toString(Arrays.java:4511)
        at dalvik.system.DexPathList.toString(DexPathList.java:201)
        at java.lang.String.valueOf(String.java:2896)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at aDK.f(PG:31)
        at aDK.<init>(PG:2)
        at aDJ.a(PG:4)
        at aAZ.run(Unknown Source:24)
        at org.chromium.base.ThreadUtils.a(PG:10)
        at xN.c(PG:113)
        at xN.b(PG:180)
        at xN.e(PG:197)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(PG:214)
        at android.webkit.WebView.enableSlowWholeDocumentDraw(WebView.java:1888)
        at org.mozilla.focus.web.WebViewProvider.create(WebViewProvider.java:52)
        at org.mozilla.focus.web.WebViewProvider.create(WebViewProvider.java:46)
        at org.mozilla.focus.activity.MainActivity$MainTabViewProvider.create(MainActivity.java:1185)
        at org.mozilla.rocket.tabs.SessionManager.initializeEngineView(SessionManager.kt:262)
        at org.mozilla.rocket.tabs.SessionManager.access$initializeEngineView(SessionManager.kt:37)
        at org.mozilla.rocket.tabs.SessionManager$Notifier.focusTab(SessionManager.kt:485)
        at org.mozilla.rocket.tabs.SessionManager$Notifier.handleMessage(SessionManager.kt:445)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-04-15 18:22:43.618 904-5288/? W/ActivityManager: handleApplicationStrictModeViolation; res=0
2019-04-15 18:22:43.621 1806-1806/org.mozilla.rocket.debug.tyu D/StrictMode: StrictMode policy violation; ~duration=272 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:241)
        at java.io.File.isDirectory(File.java:845)
        at dalvik.system.DexPathList$Element.toString(DexPathList.java:681)
        at java.lang.String.valueOf(String.java:2896)
        at java.util.Arrays.toString(Arrays.java:4511)
        at dalvik.system.DexPathList.toString(DexPathList.java:201)
        at java.lang.String.valueOf(String.java:2896)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at aDK.f(PG:31)
        at aDK.<init>(PG:2)
        at aDJ.a(PG:4)
        at aAZ.run(Unknown Source:24)
        at org.chromium.base.ThreadUtils.a(PG:10)
        at xN.c(PG:113)
        at xN.b(PG:180)
        at xN.e(PG:197)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(PG:214)
        at android.webkit.WebView.enableSlowWholeDocumentDraw(WebView.java:1888)
        at org.mozilla.focus.web.WebViewProvider.create(WebViewProvider.java:52)
        at org.mozilla.focus.web.WebViewProvider.create(WebViewProvider.java:46)
        at org.mozilla.focus.activity.MainActivity$MainTabViewProvider.create(MainActivity.java:1185)
        at org.mozilla.rocket.tabs.SessionManager.initializeEngineView(SessionManager.kt:262)
        at org.mozilla.rocket.tabs.SessionManager.access$initializeEngineView(SessionManager.kt:37)
        at org.mozilla.rocket.tabs.SessionManager$Notifier.focusTab(SessionManager.kt:485)
        at org.mozilla.rocket.tabs.SessionManager$Notifier.handleMessage(SessionManager.kt:445)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-04-15 18:22:45.127 1806-1806/org.mozilla.rocket.debug.tyu D/StrictMode: StrictMode policy violation; ~duration=272 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:241)
        at java.io.File.isDirectory(File.java:845)
        at dalvik.system.DexPathList$Element.toString(DexPathList.java:681)
        at java.lang.String.valueOf(String.java:2896)
        at java.util.Arrays.toString(Arrays.java:4511)
        at dalvik.system.DexPathList.toString(DexPathList.java:201)
        at java.lang.String.valueOf(String.java:2896)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at aDK.f(PG:31)
        at aDK.<init>(PG:2)
        at aDJ.a(PG:4)
        at aAZ.run(Unknown Source:24)
        at org.chromium.base.ThreadUtils.a(PG:10)
        at xN.c(PG:113)
        at xN.b(PG:180)
        at xN.e(PG:197)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(PG:214)
        at android.webkit.WebView.enableSlowWholeDocumentDraw(WebView.java:1888)
        at org.mozilla.focus.web.WebViewProvider.create(WebViewProvider.java:52)
        at org.mozilla.focus.web.WebViewProvider.create(WebViewProvider.java:46)
        at org.mozilla.focus.activity.MainActivity$MainTabViewProvider.create(MainActivity.java:1185)
        at org.mozilla.rocket.tabs.SessionManager.initializeEngineView(SessionManager.kt:262)
        at org.mozilla.rocket.tabs.SessionManager.access$initializeEngineView(SessionManager.kt:37)
        at org.mozilla.rocket.tabs.SessionManager$Notifier.focusTab(SessionManager.kt:485)
        at org.mozilla.rocket.tabs.SessionManager$Notifier.handleMessage(SessionManager.kt:445)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-04-15 18:22:46.347 1806-1806/org.mozilla.rocket.debug.tyu D/StrictMode: StrictMode policy violation; ~duration=272 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:241)
        at java.io.File.isDirectory(File.java:845)
        at dalvik.system.DexPathList$Element.toString(DexPathList.java:681)
        at java.lang.String.valueOf(String.java:2896)
        at java.util.Arrays.toString(Arrays.java:4511)
        at dalvik.system.DexPathList.toString(DexPathList.java:201)
        at java.lang.String.valueOf(String.java:2896)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at aDK.f(PG:31)
        at aDK.<init>(PG:2)
        at aDJ.a(PG:4)
        at aAZ.run(Unknown Source:24)
        at org.chromium.base.ThreadUtils.a(PG:10)
        at xN.c(PG:113)
        at xN.b(PG:180)
        at xN.e(PG:197)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(PG:214)
        at android.webkit.WebView.enableSlowWholeDocumentDraw(WebView.java:1888)
        at org.mozilla.focus.web.WebViewProvider.create(WebViewProvider.java:52)
        at org.mozilla.focus.web.WebViewProvider.create(WebViewProvider.java:46)
        at org.mozilla.focus.activity.MainActivity$MainTabViewProvider.create(MainActivity.java:1185)
        at org.mozilla.rocket.tabs.SessionManager.initializeEngineView(SessionManager.kt:262)
        at org.mozilla.rocket.tabs.SessionManager.access$initializeEngineView(SessionManager.kt:37)
        at org.mozilla.rocket.tabs.SessionManager$Notifier.focusTab(SessionManager.kt:485)
        at org.mozilla.rocket.tabs.SessionManager$Notifier.handleMessage(SessionManager.kt:445)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-04-15 18:22:47.735 1806-1806/org.mozilla.rocket.debug.tyu D/StrictMode: StrictMode policy violation; ~duration=272 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:241)
        at java.io.File.isDirectory(File.java:845)
        at dalvik.system.DexPathList$Element.toString(DexPathList.java:681)
        at java.lang.String.valueOf(String.java:2896)
        at java.util.Arrays.toString(Arrays.java:4511)
        at dalvik.system.DexPathList.toString(DexPathList.java:201)
        at java.lang.String.valueOf(String.java:2896)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at aDK.f(PG:31)
        at aDK.<init>(PG:2)
        at aDJ.a(PG:4)
        at aAZ.run(Unknown Source:24)
        at org.chromium.base.ThreadUtils.a(PG:10)
        at xN.c(PG:113)
        at xN.b(PG:180)
        at xN.e(PG:197)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(PG:214)
        at android.webkit.WebView.enableSlowWholeDocumentDraw(WebView.java:1888)
        at org.mozilla.focus.web.WebViewProvider.create(WebViewProvider.java:52)
        at org.mozilla.focus.web.WebViewProvider.create(WebViewProvider.java:46)
        at org.mozilla.focus.activity.MainActivity$MainTabViewProvider.create(MainActivity.java:1185)
        at org.mozilla.rocket.tabs.SessionManager.initializeEngineView(SessionManager.kt:262)
        at org.mozilla.rocket.tabs.SessionManager.access$initializeEngineView(SessionManager.kt:37)
        at org.mozilla.rocket.tabs.SessionManager$Notifier.focusTab(SessionManager.kt:485)
        at org.mozilla.rocket.tabs.SessionManager$Notifier.handleMessage(SessionManager.kt:445)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-04-15 18:22:47.732 904-5288/? W/ActivityManager: handleApplicationStrictModeViolation; res=0
2019-04-15 18:22:49.120 904-5288/? W/ActivityManager: handleApplicationStrictModeViolation; res=0
2019-04-15 18:22:49.124 1806-1806/org.mozilla.rocket.debug.tyu D/StrictMode: StrictMode policy violation; ~duration=272 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:241)
        at java.io.File.isDirectory(File.java:845)
        at dalvik.system.DexPathList$Element.toString(DexPathList.java:681)
        at java.lang.String.valueOf(String.java:2896)
        at java.util.Arrays.toString(Arrays.java:4511)
        at dalvik.system.DexPathList.toString(DexPathList.java:201)
        at java.lang.String.valueOf(String.java:2896)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at aDK.f(PG:31)
        at aDK.<init>(PG:2)
        at aDJ.a(PG:4)
        at aAZ.run(Unknown Source:24)
        at org.chromium.base.ThreadUtils.a(PG:10)
        at xN.c(PG:113)
        at xN.b(PG:180)
        at xN.e(PG:197)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(PG:214)
        at android.webkit.WebView.enableSlowWholeDocumentDraw(WebView.java:1888)
        at org.mozilla.focus.web.WebViewProvider.create(WebViewProvider.java:52)
        at org.mozilla.focus.web.WebViewProvider.create(WebViewProvider.java:46)
        at org.mozilla.focus.activity.MainActivity$MainTabViewProvider.create(MainActivity.java:1185)
        at org.mozilla.rocket.tabs.SessionManager.initializeEngineView(SessionManager.kt:262)
        at org.mozilla.rocket.tabs.SessionManager.access$initializeEngineView(SessionManager.kt:37)
        at org.mozilla.rocket.tabs.SessionManager$Notifier.focusTab(SessionManager.kt:485)
        at org.mozilla.rocket.tabs.SessionManager$Notifier.handleMessage(SessionManager.kt:445)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-04-15 18:22:50.528 1806-1806/org.mozilla.rocket.debug.tyu D/StrictMode: StrictMode policy violation; ~duration=271 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:241)
        at java.io.File.isDirectory(File.java:845)
        at dalvik.system.DexPathList$Element.toString(DexPathList.java:681)
        at java.lang.String.valueOf(String.java:2896)
        at java.util.Arrays.toString(Arrays.java:4511)
        at dalvik.system.DexPathList.toString(DexPathList.java:201)
        at java.lang.String.valueOf(String.java:2896)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at aDK.f(PG:31)
        at aDK.<init>(PG:2)
        at aDJ.a(PG:4)
        at aAZ.run(Unknown Source:24)
        at org.chromium.base.ThreadUtils.a(PG:10)
        at xN.c(PG:113)
        at xN.b(PG:180)
        at xN.e(PG:197)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(PG:214)
        at android.webkit.WebView.enableSlowWholeDocumentDraw(WebView.java:1888)
        at org.mozilla.focus.web.WebViewProvider.create(WebViewProvider.java:52)
        at org.mozilla.focus.web.WebViewProvider.create(WebViewProvider.java:46)
        at org.mozilla.focus.activity.MainActivity$MainTabViewProvider.create(MainActivity.java:1185)
        at org.mozilla.rocket.tabs.SessionManager.initializeEngineView(SessionManager.kt:262)
        at org.mozilla.rocket.tabs.SessionManager.access$initializeEngineView(SessionManager.kt:37)
        at org.mozilla.rocket.tabs.SessionManager$Notifier.focusTab(SessionManager.kt:485)
        at org.mozilla.rocket.tabs.SessionManager$Notifier.handleMessage(SessionManager.kt:445)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-04-15 18:22:50.525 904-5288/? W/ActivityManager: handleApplicationStrictModeViolation; res=0
2019-04-15 18:22:52.081 904-5288/? W/ActivityManager: handleApplicationStrictModeViolation; res=0
2019-04-15 18:22:52.083 1806-1806/org.mozilla.rocket.debug.tyu D/StrictMode: StrictMode policy violation; ~duration=271 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:241)
        at java.io.File.isDirectory(File.java:845)
        at dalvik.system.DexPathList$Element.toString(DexPathList.java:681)
        at java.lang.String.valueOf(String.java:2896)
        at java.util.Arrays.toString(Arrays.java:4511)
        at dalvik.system.DexPathList.toString(DexPathList.java:201)
        at java.lang.String.valueOf(String.java:2896)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at aDK.f(PG:31)
        at aDK.<init>(PG:2)
        at aDJ.a(PG:4)
        at aAZ.run(Unknown Source:24)
        at org.chromium.base.ThreadUtils.a(PG:10)
        at xN.c(PG:113)
        at xN.b(PG:180)
        at xN.e(PG:197)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(PG:214)
        at android.webkit.WebView.enableSlowWholeDocumentDraw(WebView.java:1888)
        at org.mozilla.focus.web.WebViewProvider.create(WebViewProvider.java:52)
        at org.mozilla.focus.web.WebViewProvider.create(WebViewProvider.java:46)
        at org.mozilla.focus.activity.MainActivity$MainTabViewProvider.create(MainActivity.java:1185)
        at org.mozilla.rocket.tabs.SessionManager.initializeEngineView(SessionManager.kt:262)
        at org.mozilla.rocket.tabs.SessionManager.access$initializeEngineView(SessionManager.kt:37)
        at org.mozilla.rocket.tabs.SessionManager$Notifier.focusTab(SessionManager.kt:485)
        at org.mozilla.rocket.tabs.SessionManager$Notifier.handleMessage(SessionManager.kt:445)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-04-15 18:22:53.521 1806-1806/org.mozilla.rocket.debug.tyu D/StrictMode: StrictMode policy violation; ~duration=271 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:241)
        at java.io.File.isDirectory(File.java:845)
        at dalvik.system.DexPathList$Element.toString(DexPathList.java:681)
        at java.lang.String.valueOf(String.java:2896)
        at java.util.Arrays.toString(Arrays.java:4511)
        at dalvik.system.DexPathList.toString(DexPathList.java:201)
        at java.lang.String.valueOf(String.java:2896)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at aDK.f(PG:31)
        at aDK.<init>(PG:2)
        at aDJ.a(PG:4)
        at aAZ.run(Unknown Source:24)
        at org.chromium.base.ThreadUtils.a(PG:10)
        at xN.c(PG:113)
        at xN.b(PG:180)
        at xN.e(PG:197)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(PG:214)
        at android.webkit.WebView.enableSlowWholeDocumentDraw(WebView.java:1888)
        at org.mozilla.focus.web.WebViewProvider.create(WebViewProvider.java:52)
        at org.mozilla.focus.web.WebViewProvider.create(WebViewProvider.java:46)
        at org.mozilla.focus.activity.MainActivity$MainTabViewProvider.create(MainActivity.java:1185)
        at org.mozilla.rocket.tabs.SessionManager.initializeEngineView(SessionManager.kt:262)
        at org.mozilla.rocket.tabs.SessionManager.access$initializeEngineView(SessionManager.kt:37)
        at org.mozilla.rocket.tabs.SessionManager$Notifier.focusTab(SessionManager.kt:485)
        at org.mozilla.rocket.tabs.SessionManager$Notifier.handleMessage(SessionManager.kt:445)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-04-15 18:22:54.876 1806-1806/org.mozilla.rocket.debug.tyu D/StrictMode: StrictMode policy violation; ~duration=271 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:241)
        at java.io.File.isDirectory(File.java:845)
        at dalvik.system.DexPathList$Element.toString(DexPathList.java:681)
        at java.lang.String.valueOf(String.java:2896)
        at java.util.Arrays.toString(Arrays.java:4511)
        at dalvik.system.DexPathList.toString(DexPathList.java:201)
        at java.lang.String.valueOf(String.java:2896)
        at java.lang.StringBuilder.append(StringBuilder.java:132)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at aDK.f(PG:31)
        at aDK.<init>(PG:2)
        at aDJ.a(PG:4)
        at aAZ.run(Unknown Source:24)
        at org.chromium.base.ThreadUtils.a(PG:10)
        at xN.c(PG:113)
        at xN.b(PG:180)
        at xN.e(PG:197)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(PG:214)
        at android.webkit.WebView.enableSlowWholeDocumentDraw(WebView.java:1888)
        at org.mozilla.focus.web.WebViewProvider.create(WebViewProvider.java:52)
        at org.mozilla.focus.web.WebViewProvider.create(WebViewProvider.java:46)
        at org.mozilla.focus.activity.MainActivity$MainTabViewProvider.create(MainActivity.java:1185)
        at org.mozilla.rocket.tabs.SessionManager.initializeEngineView(SessionManager.kt:262)
        at org.mozilla.rocket.tabs.SessionManager.access$initializeEngineView(SessionManager.kt:37)
        at org.mozilla.rocket.tabs.SessionManager$Notifier.focusTab(SessionManager.kt:485)
        at org.mozilla.rocket.tabs.SessionManager$Notifier.handleMessage(SessionManager.kt:445)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-04-15 18:22:56.162 904-5288/? W/ActivityManager: handleApplicationStrictModeViolation; res=0

**Comment by mTwTm** [comment]
Only happen when UrlInput is not yet clicked.

**Comment by mTwTm** [comment]
I'm going to temp allow this but I'll keep this ticket open.
