### ISSUE TITLE
Cannot see screenshots on Nexus 5

### ISSUE THREAD

**Issue by walkingice** [mozilla-mobile/FirefoxLite#714]
I can reproduce this issue on Nexus 5, but it works on Google Pixel.

1. open app, go to 'https://mozilla.org'
2. take screenshot
3. go to My-shots, try to open the screenshot

expect result: be able to see the screenshot
actual result: the viewer just close and back to screenshot list

configuration: Nexus 5, AOSP 6.0.1

logcat

```
09-11 18:58:00.309 20527 20696 W ExifInterface: Invalid image.
09-11 18:58:00.309 20527 20696 W ExifInterface: java.io.IOException: Invalid marker: 89
09-11 18:58:00.309 20527 20696 W ExifInterface:         at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1600)
09-11 18:58:00.309 20527 20696 W ExifInterface:         at android.media.ExifInterface.loadAttributes(ExifInterface.java:1339)
09-11 18:58:00.309 20527 20696 W ExifInterface:         at android.media.ExifInterface.<init>(ExifInterface.java:1057)
09-11 18:58:00.309 20527 20696 W ExifInterface:         at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.getExifOrientation(SubsamplingScaleImageView.java:1807)
09-11 18:58:00.309 20527 20696 W ExifInterface:         at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.access$5200(SubsamplingScaleImageView.java:81)
09-11 18:58:00.309 20527 20696 W ExifInterface:         at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.jav
a:1520)
09-11 18:58:00.309 20527 20696 W ExifInterface:         at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.jav
a:1492)
09-11 18:58:00.309 20527 20696 W ExifInterface:         at android.os.AsyncTask$2.call(AsyncTask.java:295)
09-11 18:58:00.309 20527 20696 W ExifInterface:         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-11 18:58:00.309 20527 20696 W ExifInterface:         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
09-11 18:58:00.309 20527 20696 W ExifInterface:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-11 18:58:00.309 20527 20696 W ExifInterface:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-11 18:58:00.309 20527 20696 W ExifInterface:         at java.lang.Thread.run(Thread.java:818)
09-11 18:58:00.368 20527 20536 E StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
09-11 18:58:00.368 20527 20536 E StrictMode: java.lang.Throwable: Explicit termination method 'close' not called
09-11 18:58:00.368 20527 20536 E StrictMode:    at dalvik.system.CloseGuard.open(CloseGuard.java:180)
09-11 18:58:00.368 20527 20536 E StrictMode:    at java.io.FileInputStream.<init>(FileInputStream.java:78)
09-11 18:58:00.368 20527 20536 E StrictMode:    at java.io.FileInputStream.<init>(FileInputStream.java:103)
09-11 18:58:00.368 20527 20536 E StrictMode:    at android.media.ExifInterface.loadAttributes(ExifInterface.java:1338)
09-11 18:58:00.368 20527 20536 E StrictMode:    at android.media.ExifInterface.<init>(ExifInterface.java:1057)
09-11 18:58:00.368 20527 20536 E StrictMode:    at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.getExifOrientation(SubsamplingScaleImageView.java:1807)
09-11 18:58:00.368 20527 20536 E StrictMode:    at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.access$5200(SubsamplingScaleImageView.java:81)
09-11 18:58:00.368 20527 20536 E StrictMode:    at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1520)
09-11 18:58:00.368 20527 20536 E StrictMode:    at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1492)
09-11 18:58:00.368 20527 20536 E StrictMode:    at android.os.AsyncTask$2.call(AsyncTask.java:295)
09-11 18:58:00.368 20527 20536 E StrictMode:    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-11 18:58:00.368 20527 20536 E StrictMode:    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
09-11 18:58:00.368 20527 20536 E StrictMode:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-11 18:58:00.368 20527 20536 E StrictMode:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-11 18:58:00.368 20527 20536 E StrictMode:    at java.lang.Thread.run(Thread.java:818)
09-11 18:58:00.368 20527 20536 W System.err: StrictMode VmPolicy violation with POLICY_DEATH; shutting down.
09-11 18:58:00.368 20527 20536 I Process : Sending signal. PID: 20527 SIG: 9
```

**Comment by chianger** [comment]
decision pending until we clarify whether it's only reproducible under strict mode.

**Comment by chianger** [comment]
triage: only happens on debug build so s3.

**Comment by walkingice** [comment]
https://android.googlesource.com/platform/frameworks/base/+/android-6.0.1_r81/media/java/android/media/ExifInterface.java#1338

try to trace the source code, it seems that its `IoUtils.closeQuietly(in);` does not work for some reason, and which hits StrictMode policy. I don't think we can do anything for framework on some specific version.
